export const MODAL = [
  {
    alt: 'Black Jeans - Ambiwalentnie',
    src: 'https://player.vimeo.com/video/388824268',
    title: 'Teledysk do utworu Ambiwalentnie zespołu Black Jeans.',
    production: [
      'Produkcja: CINEBIT STUDIO',
      'Scenariusz: Rafał Florkiewicz',
      'Autor zdjęć: Andrzej Michalecki',
      'Operator kamery: Tomasz Januszewski',
      'Casting & Produkcja: Adrianna Minkiewicz',
      'Asystent produkcji: Joanna Łącka',
      'Asystent kamery i oświetlenia: Filip Wasilewski',
      'Montaż: Andrzej Michalecki',
      'Korekcja barwna: Andrzej Michalecki',
      'Asystent techniczny: Janusz Gietka, Konrad Forystek'
    ],
    cast: [
      'Kristina Kaminskaite',
      'Alex Ochman',
      'Zuzia Pająk',
      'Kuba Kaszak',
    ]
  },
  {
    alt: 'Black Jeans - Grzech',
    src: 'https://player.vimeo.com/video/388027864',
    title: 'Teledysk do utworu Black Jeans zespołu Black Jeans.',
    production: [
      'Produkcja: Cinebit Studio',
      'Reżyser: Artur Czerwiński',
      'Scenariusz: Artur Czerwiński',
      'Autor zdjęć: Tomasz Januszewski',
      'Casting: Adrianna Minkiewicz',
      'Producent: Łukasz Szczęsny',
      'Kierownik produkcji: Adrianna Minkiewicz',
      'Asystent produkcji: Dominika Zajczuk',
      'Scenograf: Marcin Malisz',
      'Kostiumograf: Aleksandra Sałacińska',
      'Charakteryzator: Karolina Wysocki',
      'Rekwizytor: Marcin Malisz / Andrzej “Andy” Michalecki',
      'Operator kamery: Filip Wasilewski / Filip Rogoziński',
      'Asystent kamery: Kamil “Młody” Galach / Jakub Skowronek',
      'Ostrzyciel: Filip Rogoziński',
      'Mistrz oświetlenia: Tomasz Januszewski',
      'Kierownik planu: Rafał Florkiewicz',
      'Postprodukcja: Andrzej “Andy Michalecki” / Filip Wasilewski',
      'Montażysta: Andrzej “Andy Michalecki” / Filip Wasilewski',
      'Kolorysta: Tomasz Januszewski',
      'Foto: Emilia Abłażewicz / Alena Kaliska',
    ],
    cast: [
      'Dominika Kryszczyńska',
      'Karol Zakrzewski',
    ],
    special: [
      'TVPW',
      'RekwizytorniA (rekwizytorniapraga.pl)',
    ]
  },
  {
    alt: 'Harnaś - Przełam rutynę!',
    src: 'https://player.vimeo.com/video/388823919',
    title: 'Drugie miejsce w konkursie na reklamę piwa Harnaś na platformie MilionYou!',
    production: [
      'Produkcja: Cinebit Studio',
      'DIR: Artur Czerwiński',
      'DOP: Tomasz Januszewski',
      'Kierownik produkcji: Kasia Bielińska',
      'Szwenk: Mateusz Strzałka',
      'Gaffer/AC: Kuba Lempke Filip Wasilewski',
      'Scenografia/Kostiumy: Zosia Kochman Zuzanna Kornelia Kolanowska',
      'Technik: Bartosz Wojciechowski',
      'Asystent Kierownika Produkcji: Kasia Gorczyńska Ola Dobiasz',
      'Fotosy: Emilia Abłażewicz',
      'Lokacja: Filip Lipiecki',
      'Montaż: Mateusz Strzałka',
      'VFX: Robert Czerwiński',
      'Kolor korekcja: Tomasz Januszewski',
      'Udźwiękowienie: Mateusz Strzałka'
    ],
    cast: null,
    special: null
  },
  {
    alt: 'Knorr - Mistrzowie kuchni',
    src: 'https://player.vimeo.com/video/388829493',
    title: 'Reklama zrealizowana dla Knorra w ramach konkursu na platformie MilionYou.',
    production: [
      'Produkcja: Cinebit Studio',
      'Dir: Artur Czerwiński',
      'Dop: Tomasz Januszewski',
      'Kierownik produkcji: Kasia Bielińska',
      'Szwenk: Janusz Gietka Mateusz Sadowski',
      'Scenografia: Emilia Abłażewicz',
      'Gaffer: Filip Wasilewski Kuba Lempke',
      'Makeup: Joanna Kulasza',
      'Fotosy: Emilia Abłażewicz Fotografia',
      'VFX: Robert Czerwiński Kamil Zawistowski Kamil Kłoczewiak',
      'Kolor korekcja: Tomasz Januszewski',
      'Online: Filip Wasilewski Artur Czerwiński'
    ],
    cast: [
      'Filip Wasilewski',
      'Kuba Lempke',
      'Kasia Bielińska',
      'Krzysztof Tarwacki',
      'Joanna Kulasza',
      'Michał Walter',
      'Filip Lipiecki'
    ],
    special: null
  },
  {
    alt: 'Redleaf - Zamieszanie',
    src: 'https://player.vimeo.com/video/399341592',
    title: 'Redleaf - Zamieszanie',
    production: [
      'DIR: Artur Czerwiński',
      'DOP: Tomasz Januszewski',
      'Kierownik produkcji: Kasia Bielińska',
      'Asystent Kierownika Produkcji: Weronika Danilowska',
      'Kierownik Planu: Paulina Lendzion',
      'Operator Kamery: Andrzej \'Andy\' Michalecki',
      'Asystent Kamery: Filip Wasilewski',
      'Mistrz oświetlenia: Tomasz Januszewski',
      'Gaffer: Kuba Duczmalewski Rafał Hrehoruk',
      'Inżynier Planu: Kamil Galach Janusz Gietka',
      'Charakteryzacja: Natalie Łasiewicz Oliwia Bugaj',
      'Kostiumy: Ola Sałacińska',
      'Scenografia/rekwizyty: Emilia Abłażewicz',
      'Dźwięk: Tomasz Junker',
      'Fotosy: Emilia Abłażewicz',
      'Making of: Adam Gottscholl',
      'Montaż: Filip Wasilewski Artur Czerwiński',
      'Kolor: Tomasz Januszewski',
      'Vfx: Robert Czerwiński',
      'Udźwiękowienie: Artur Czerwiński Filip Wasilewski',
      'Transport: Mateusz Marciniak Tomek Konopka',
    ],
    cast: [
      'Krzysztof Rysz',
      'Jerzy Wojtkowski',
      'Elżbieta Rutkowska',
      'Elżbieta Studniarek',
      'Elżbieta Parol',
      'Artur Czerwiński',
      'Katarzyna Bielińska',
      'Sekunjav Reto',
      'Francis Aniakudo',
      'Kuba Lempke',
      'kotka Maja, właścicielka Aleksandra Stawczyk',
      'suczka Pepper, właścicielka Martyna Zowade',
    ],
    special: [
      'Podziękowania dla restauracji Lotos za użyczenie wspaniałej lokacji!'
    ]
  },
  {
    alt: 'Somersby - Kalambury',
    src: 'https://player.vimeo.com/video/388825454',
    title: 'Pierwsze miejsce w konkursie na reklamę Somersby na platformie MilionYou.',
    production: [
      'Dir: Artur Czerwiński',
      'Dop: Ola Kamińska',
      'Kierwonik Produkcji: Kasia Bielińska',
      'II Reżyser: Wojtek Jastrzębski',
      'Kierownik planu: Aga Krzelowska',
      'Klaps/script: Brunon Hawryluk',
      'Szwenk: Gaweł Józefczuk',
      'Ostrzyciel: Piotr Michalak',
      'Mistrz oświetlenia: Jacek Szpros',
      'Gaffer: Filip Rogoziński, Rafał Hrehoruk',
      'Inżynier planu: Tomash Flis',
      'Dźwięk na planie: Filip Marszałek',
      'Tyczkarz: Tomek Murawski',
      'Scenografia: Zosia Kochman',
      'Kostiumy: Basia Pospieszalska',
      'Lokacja: Filip Lipiecki',
      'Make up: Asia Czerwonka, Ola Kułak',
      'Montaż: Mateusz Strzałka',
      'Korekcja barwna: Tomasz Januszewski',
      'Udźwiękowienie: Wojciech Śliwiński'
    ],
    cast: [
      'Andrzej \'Andy\' Michalecki',
      'Antoni Gustowski',
      'Sonia Felbur',
      'Marta Kosiorek',
      'Paula Wojciechowska',
      'Sebastian Golański',
      'Robert Czerwiński'
    ],
    special: null
  },
  {
    alt: 'Paweł Tur - Tanki',
    src: 'https://player.vimeo.com/video/402689876',
    title: 'Paweł Tur - Tanki',
    production: [
      'Scenariusz i reżyseria: Artur Czerwiński',
      'Zdjęcia: Andrzej Michalecki',
      'Casting: Adrianna Minkiewicz',
      'Producent: Grzegorz Tyluś',
      'Kierownictwo produkcji: Adrianna Minkiewicz',
      'Scenografia: Gabriela Łukasz, Adrianna Minkiewicz',
      'Kostiumy: Katarzyna Cygańska',
      'Charakteryzacja: Agata Kozłowska',
      'Montaż: Andrzej Michalecki',
      'II reżyser: Brunon Hawryluk',
      'Kierownik planu: Konrad Wielki',
      'Operator kamery (I Unit): Dawid Cechmajster',
      'Operator kamery (II Unit): Tomasz Januszewski',
      'Asystent operatora obrazu/ Ostrzyciel: Filip Rogoziński',
      'Ostrzyciel (II Unit): Jacek Kowalczyk',
      'Asystent kamery: Filip Wasilewski',
      'Asystent kamery II: Jakub Duczmalewski',
      'Mistrz oświetlenia: Zbigniew Ratkiewicz',
      'Oświetlacze: Adam Ratkiewicz, Michał Kałucki',
      'Make-up: Dominika Jedynak, Magdalena Piętak',
      'Fotosy: Emilia Abłażewicz, Jacek Kowalczyk',
      'Storyboard: Robert Czerwiński',
      'Postprodukcja: Dawid Cechmajster',
      'Kolorkorekcja: Dawid Cechmajster',
      'Sprzęt kamerowy: Little Beast',
      'Oświetlenie: Open Media'
    ],
    cast: [
      'Kamila Mruszczyk',
      'Daniel Skrzypczak',
      'Karolina Ficht',
      'Zuzia Pająk',
      'Julia Milewska',
      'Zuzia Milewska',
      'Marcin Zaprawa',
      'Pola Cegielska',
      'Dominik Cegielski',
      'Konrad Chmioła',
      'Krzysztof Daniszewski',
      'Wiktor Dobrowolski',
      'Rafał Florkiewicz',
      'Adam Gottscholl',
      'Grzegorz Grochowski',
      'Joanna Herman',
      'Marta Kobylińska',
      'Aneta Kostow',
      'Magdalena Kostyra',
      'Tomasz Łukaszek',
      'Wojciech Majkowski',
      'Gabriela Milczarek',
      'Alex Ochman',
      'Piotr Pająk',
      'Hanna Piprowska',
      'Andrzej Skibiński',
      'Kacper Szewczyk',
      'Maja Tyluś',
      'Sebastian Wrona',
      'Marek Zalewski',
      'Radosław Zalewski',
      'Vladyslav Zavouriev'
    ],
    special: [
      'Specjalne podziękowania dla: Maciej Bujwan'
    ]
  },
  {
    alt: 'Sprite - Otwieracze',
    src: 'https://player.vimeo.com/video/388826598',
    title: 'Reklama realizowana w ramach konkursu Papaya Young Directors 5 w 2018 roku.',
    production: [
      'Produkcja Cinebit Studio',
      'Reżyser – Artur Czerwiński',
      'II Reżyser – Wojciech Jastrzębski',
      'Producent – Artur Czerwiński',
      'Kierownik produkcji – Katarzyna Bielińska',
      'Asystenci Kierownika Produkcji – Alicja Pytka, Justyna Szlaszyńska, Tomasz Stopczyński, Aleksandra Stefanowska, Hubert Wyrzykowski, Aga Krzelowska, Ada Zalewska, Magda Ruszczak',
      'Casting – Artur Czerwiński, Milena Składanek, Alicja Pytka',
      'Klaps/Script - Joanna Kulasza',
      'Autor zdjęć – Jacek Kowalczyk',
      'Kierownik Planu – Tomasz Stopczyński',
      'Scenograf – Małgorzata Dąbrowska',
      'Kostiumograf - Margarita Barska',
      'Charakteryzator – Aleksandra Kułak, Maja Majchrzak',
      'Rekwizytor – Małgorzata Dąbrowska',
      'Operator kamery – Aleksandra Kamińska',
      'Asystent kamery – Michał Piotrkowski',
      'Ostrzyciel – Gaweł Józefczuk',
      'Mistrz oświetlenia – Tomasz Januszewski',
      'Grip – Filip Rogoziński, Jan Miklusz',
      'Inżynier planu – Piotr Grygo, Rafał Hrehoruk',
      'Making-off – Hubert Wyrzykowski',
      'Fotosy – Marcin Nalepa, Matteo Panzironi',
      'Postprodukcja/Compositing – Robert Czerwiński, Norbert Świerczek',
      'Montażysta – Marta Ossowska',
      'Kolorysta – Piotr Nowicki / MIŁO',
      'On line – Artur Czerwiński',
      'Realizator dźwięku plan – Paweł Sota',
      'Tyczkarz - Jan Machalski, Tomasz Murawski',
      'Udźwiękowienie – Dariusz Podhajski, Paulina Wyszkowska / GŁOŚNO',
      'Muzyka / Kompozytor – DCODE MUSIC',
      'Partner Główny - SPRITE'
    ],
    cast: [
      'Szymon Kołodziej',
      'Daniel Dziorek',
      'Taras Piont',
      'Daniel Skrzypczak',
      'Adrianna Malecka',
      'Dorota Bzdyla',
      'Dorota Krempa',
      'Kot Erwin',
      'Krzysztof Tarwacki',
      'Marcin Orzełowski',
      'Wojciech Karpiński',
      'Patryk Paliga',
      'Paweł Możejko',
      'Maciej Lenart',
      'Piotr Olkiewicz',
      'Tomasz Junker',
      'Michał Walter',
      'Oskar Lewandowski',
      'Aleksander Giedrojć',
      'Piotr Frączkowski',
      'Piotr Stępiński',
      'Milena Lewandowska',
      'Malwina Dutkiewicz',
      'Klaudia Bielnicka',
      'Monika Marciniak',
      'Aida Boral',
      'Magdalena Rucło',
      'Daria Brun',
      'Joanna Kacprowska',
      'Jasmin Hosin',
      'Ula Gogowska',
      'Adrianna Omietańska',
      'Joanna Rosińska',
      'Angelika Tracz',
      'Justyna Przybysz',
      'Ania Markowicz'
    ],
    special: [
      'ATM Studio',
      'Heliograf',
      'TVPW',
      'MIŁO',
      'GŁOŚNO',
      'VENDO.TV',
      'DCODE MUSIC',
      'Onet',
      'Psycho-Media',
      'Lunchtime.com',
      'MAKonLine Ubezpieczenia',
      'Zuzanna Gąsiorek',
      'Kateryna Metelska',
      'Łukasz Czerwiński'
    ]
  },
  {
    alt: 'Sigals - Bieg lat',
    src: 'https://player.vimeo.com/video/388825157',
    title: 'Teledysk Bieg Lat dla zespołu Sigals',
    production: [
      'Reżyseria, scenariusz - Artur Czerwiński',
      'Zdjęcia, kolor korekcja, oświetlenie - Tomasz “TJ”Januszewski',
      'Kierownik produkcji - Kasia Bielińska',
      'Montaż - Filip Wasilewski',
      'Operatorzy kamery - Kuba Lempke, Filip Wasilewski',
      'Asystent kamery - Jacek Gruchalski',
      'Ostrzyciel - Filip Rogoziński',
      'Kierownik planu - Agnieszka Krzelowska',
      'Scenografia - Zofia Kochman, Zuzanna Kolanowska, Zuzanna Zajt',
      'Kostiumy - Zuzanna Kolanowska, Marta Karaban',
      'Inżynier planu - Tomasz Murawski, Kamil Galach',
      'Gaffer, dyżurny planu - Janusz Gietka, Maciek Karpowicz',
      'Asystent produkcji - Aleksandra Dobiasz',
      'Klaps - Kasia Gorczyńska',
      'Fotosy - Emilia Abłażewicz, Wioleta Niedźwiedź',
      'Make up - Magdalena Michalak, Joanna Czerwonka, Wiktoria Winiarska, Magda Arbaszewska, Natalia Brzęczkowska',
      'Produkcja - Paweł „Pawziu” Wiśniewski',
      'Ewa Rutkowska - wokal',
      'Asia Kulasza, Karolina Grala - chórki',
      'Paweł „Pawziu” Wiśniewski - instrumenty klawiszowe',
      'Kuba Andrzejewski - gitara',
      'Wojtek Chmielewski - gitara',
      'Piotr „Pepek” Szczepańczyk - bas',
      'Marcel Witkowski - bębny',
      'Muzyka, słowa - Paweł „Pawziu” Wiśniewski',
      'Rejestracja, miks - Paweł „Pawziu” Wiśniewski',
      'Mastering - Piotr Rychlec'
    ],
    cast: [
      'Filip Lipiecki - reżyser',
      'Michał Walter - operator kamery',
      'Michał Woś - operator kamery',
      'Maciej Karpowicz - operator kamery',
      'Tomasz Murawski - operator tyczki',
      'Filip Wasilewski - dźwiękowiec',
      'Marta Pióro - kierownik produkcji',
      'Katarzyna Górczyńska - klaps',
      'Filip Rogoziński - realizator wizji',
      'Krzysztof Rysz - zegarmistrz',
      'Krzysztof "Lazlo" Tarwacki - pracownik muzeum',
      'Michał Ferenc - pracownik muzeum',
      'Andrzej "Andy" Michalecki - barber',
      'Piotr "Radio" Radio - klient',
      'Karolina Kot - sprzątaczka',
      'Agnieszka Cesarczyk - mama',
      'Łukasz Szmigrodzki - tata',
      'Jagoda Bednarek - córka',
      'Ewa Borkowska - pacjentka w poczekalni',
      'Bogumiła Stasiewicz - pacjentka w poczekalni',
      'Elżbieta Rutkowska - pacjentka w poczekalni',
      'Katarzyna Bielińska - pacjentka w poczekalni',
      'Sergiusz Bienias - pacjent w poczekalni',
    ],
    special: [
      'TVPW za ogrom pracy i pozytywnej energii włożonych w powstanie tego klipu,',
      'Barbera Kopytek za użyczenie miejsca do nagrań,',
      'Anetty Owczynnikow za użyczenie miejsca do nagrań,',
      'Pracowni Zegarmistrzowskiej Sebastiana Huperta za użyczenie miejsca do nagrań oraz przepyszną dereniówkę,',
      'Służewskiego Domu Kultury za otwartość i życzliwość,',
      'Jakuba Mech i firmy Uplive - streaming-warszawa.pl za wsparcie techniczne,',
      'Łukasza Marca za wsparcie techniczne,',
      'Mleczarni Jerozolimskiej za pyszne obiady,',
      'Grupy Teatralnej Kontrapunkt za to, że bieg lat ich nie dotyczy,',
      'Heliografu za wypożyczenie oświetlenia,',
      'Rentalu Ja Cię Kręcę za wsparcie sprzętowe,',
      'Jacka Gruchalskiego za wsparcie sprzętowe,',
      'Rancha u Janka za transformację w studio nagrań,',
      'SoundB za wsparcie sprzętowe.'
    ]
  }
];